version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./src/back_end/Dockerfile
    image: frre_back_end:latest
    container_name: frre_back_end_container
    ports:
      - 8000:8000

  frontend:
    build:
      context: .
      dockerfile: ./src/front_end/Dockerfile
    image: frre_front_end:latest
    container_name: frre_front_end_container
    ports:
      - 8501:8501
    volumes:
      - ./src/front_end:/streamlit_app
